### ISSUE TITLE
Activity with multiple payment restrictions always uses first one

### ISSUE THREAD

**Issue by rjnl** [sebsoftnl/moodle-availability_gwpayments#4] opened 2022-03-07 03:31 UTC
I was testing whether it is possible to have multiple payment restrictions set to an activity.
So I created an activity and added payment restrictions for 
- AUD 20,
- EUR 10,
- USD 15

The user should be able to make payments in any one of the currencies. On the course page user sees 3 Select payment type buttons, one for each currency/amount. Ok, so far.

![image](https://user-images.githubusercontent.com/4531184/156963573-8e223664-a16a-43ff-99fe-f83c3110ef68.png)

However, when proceeding further, the first payment restriction currency/amount is always used, regardless of which currency/option user chooses. So if a user clicks on the Select payment for EUR 10, it will change to AUD 20 as soon as the user selects a payment gateway.

**Comment by iforwms** [comment] 2022-06-17 00:33
This issue also affects the "Check Coupon" function - when multiple payment currencies are available only the first button works. This is due to each button being identified by their ID, and I assume an event listener added to this ID. The solution would be to replace the ID with a class and add an event listener to each button with that class name.

**Comment by rogiervandongen** [comment] 2024-04-10 10:15
@iforwms 
Wrong assumption; all trigger work on the data-action set on the button, which we can do nothing about. This is the way Moodle dictates the implementation.

@rjnl 
I doubt we can find a decent fix for this unless everyting is completely rewritten but that'd involve TONS more configuration.
I won't go into details too much due to the rather poorly written "gateway framework" (which was added by Moodle themselves), but the only variables that are used, are the component, paymentarea and the itemid.
This is exactly where the issue is, because the itemId is either the ID of the section or the ID of the course module (depending on which of these levels you put the restriction set).

In other words:
- we know the component, it's "this" gateway (aka: availability_gwpayments).
- we know the paymentarea (dictated by this very plugin; it's either cmfee or sectionfee)
- we know the itemid of the "target" (section or CM)

See the issue? There's no way to distinguish anything else with this in mind.
Facilitating/fixing the above would imply you'll have to first setup a relation between ^ one of the three "restrictions", modifying the code so it uses the "itemID" of the relation and then, when handling the payment, finding a way to translate that data back to the correct scope.
And this is where all the real issues begin.... Moodle's implementation is just not capable of this; the implementation of the gateways themselves are lacking in functionality to do this "correctly".

I'm going to mark this as "won't fix", simply due to the fact Moodle's "payment gateway core" lacks too much functionality to even be able to facilitate this in a clean and correct way.

**Closed by rogiervandongen** 2024-04-10 10:15 UTC
